name: Run Action

on: push


jobs:

    run-the-action:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
          - id: hello
            uses: ./
            with:
                who-to-greet: 'World'
        
          - name: Get the output time
            run: echo "The time was ${{ steps.hello.outputs.time }}"
